In [1]:
from numpy import *

In [2]:
random.rand(4,4)

array([[0.26946364, 0.67580845, 0.37337942, 0.76190156],
       [0.54631419, 0.38170381, 0.30900433, 0.44616802],
       [0.50489556, 0.5633234 , 0.16733299, 0.37132083],
       [0.49475201, 0.706911  , 0.0315989 , 0.41151972]])

In [5]:
randMat = mat(random.rand(4,4))
randMat

matrix([[0.56125927, 0.283599  , 0.67826997, 0.22170868],
        [0.58104897, 0.87377342, 0.63992219, 0.61775484],
        [0.50208364, 0.65741004, 0.41937272, 0.40929504],
        [0.11638288, 0.09390771, 0.57785732, 0.15170901]])

In [7]:
invRandMat = randMat.I
invRandMat

matrix([[  4.32176753,   3.25738003,  -5.52685727,  -4.66894096],
        [ -6.54253418, -13.552018  ,  21.32575665,   7.21008583],
        [ -1.60636376,  -4.26726828,   5.77140705,   4.15309659],
        [  6.85301257,  22.14376076, -30.94391932, -10.10879436]])

In [10]:
myEye = randMat * invRandMat
myEye

matrix([[ 1.00000000e+00, -8.88178420e-16, -3.55271368e-15,
          1.33226763e-15],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 4.44089210e-16, -1.77635684e-15,  1.00000000e+00,
          8.88178420e-16],
        [ 4.44089210e-16, -8.88178420e-16, -8.88178420e-16,
          1.00000000e+00]])

In [11]:
myEye - eye(4)    # eye(4)创建单位矩阵

matrix([[ 8.88178420e-16, -8.88178420e-16, -3.55271368e-15,
          1.33226763e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 4.44089210e-16, -1.77635684e-15,  0.00000000e+00,
          8.88178420e-16],
        [ 4.44089210e-16, -8.88178420e-16, -8.88178420e-16,
          2.22044605e-16]])