K-均值聚类支持函数

In [1]:
import numpy as np

In [49]:
def load_dataset(filename):
    """
    加载数据集为指定格式
    """
    data_mat = []
    f = open(filename)
    for line in f.readlines():
        cur_line = line.strip().split('\t')
        flt_line = list(map(float, cur_line))
        data_mat.append(flt_line)
    return data_mat

In [83]:
def dist_eclud(vec_a, vec_b):
    """
    计算两个向量的欧氏距离
    """
    return np.sqrt(np.sum(np.power(vec_a - vec_b, 2)))

In [74]:
def rand_cent(dataset, k):
    """
    为给定数据集构建一个包含k个随机质心的集合，随机质心在整个数据集的边界之内
    """
    n = np.shape(dataset)[1]    # 数据集列数
    centroids = np.mat(np.zeros((k, n)))    # 构建簇质心
    for j in range(n):
        min_j = min(dataset[:, j])    # 每一列的最小值
        range_j = float(max(dataset[:, j]) - min_j)    # 每一列的最大最小值之差
        centroids[:, j] = np.mat(min_j + range_j * np.random.rand(k, 1))
    return centroids

In [76]:
data_mat = np.mat(load_dataset(filename = r'.\datas\testSet.txt'))
data_mat[0:5]

matrix([[ 1.658985,  4.285136],
        [-3.453687,  3.424321],
        [ 4.838138, -1.151539],
        [-5.379713, -3.362104],
        [ 0.972564,  2.924086]])

In [68]:
min(data_mat[:, 0]), max(data_mat[:, 0])

(matrix([[-5.379713]]), matrix([[4.838138]]))

In [69]:
min(data_mat[:, 1]), max(data_mat[:, 1])

(matrix([[-4.232586]]), matrix([[5.1904]]))

In [73]:
rand_cent(data_mat, 2)

matrix([[ 3.2858011 , -4.03549999],
        [-1.53311244, -1.71997865]])

In [87]:
# 计算前两个数据的欧氏距离
dist_eclud(data_mat[0], data_mat[1])

5.184632816681332

K-均值聚类算法

In [102]:
dist_means = dist_eclud
create_cent = rand_cent

m = np.shape(dataset)[1]    # 数据集列数
cluster_assment = np.mat(np.zeros((m, 2)))
centroids = create_cent(dataset, k)
cluster_changed = True
while cluster_changed:
    cluster_changed = False
    for i in range(m):
        # 寻找最近的质心
        min_dist = np.inf    # 最小距离初始化为无穷大
        min_index = -1
        for j in range(k):
            dist_ji = dist_means(centroids[j, :], dataset[i, :])    # 计算数据和质心距离
            if dist_ji < min_dist:
                min_dist = dist_ji
                min_index = j
        # end for
        if cluster_assment[i,0] != min_index:
            cluster_changed = True
        cluster_assment[i, :] = min_index, min_dist**2
    # end for
    print(centroids)
    # 更新质心位置
    for cent in range(k):
        print(cent)

[[-2.67494898 -3.60795764]
 [-0.59693551  3.1629973 ]]
0
1
[[-2.67494898 -3.60795764]
 [-0.59693551  3.1629973 ]]
0
1
